# This file is auto-generated by AWSMetadata.jl
include("../AWSServices.jl")
using .AWSServices: dataexchange

"""
    CancelJob()

This operation cancels a job. Jobs can be cancelled only when they are in the WAITING state.

Required Parameters
{
  "JobId": "The unique identifier for a job."
}
"""
CancelJob(JobId) = dataexchange("DELETE", "/v1/jobs/$(JobId)")
CancelJob(JobId, args) = dataexchange("DELETE", "/v1/jobs/$(JobId)", args)
CancelJob(a...; b...) = CancelJob(a..., b)

"""
    CreateDataSet()

This operation creates a data set.

Required Parameters
{
  "AssetType": "The type of file your data is stored in. Currently, the supported asset type is S3_SNAPSHOT.",
  "Description": "A description for the data set. This value can be up to 16,348 characters long.",
  "Name": "The name of the data set."
}

Optional Parameters
{
  "Tags": "A data set tag is an optional label that you can assign to a data set when you create it. Each tag consists of a key and an optional value, both of which you define. When you use tagging, you can also use tag-based access control in IAM policies to control access to these data sets and revisions."
}
"""
CreateDataSet(AssetType, Description, Name) = dataexchange("POST", "/v1/data-sets")
CreateDataSet(AssetType, Description, Name, args) = dataexchange("POST", "/v1/data-sets", args)
CreateDataSet(a...; b...) = CreateDataSet(a..., b)

"""
    CreateJob()

This operation creates a job.

Required Parameters
{
  "Details": "The details for the CreateJob request.",
  "Type": "The type of job to be created."
}
"""
CreateJob(Details, Type) = dataexchange("POST", "/v1/jobs")
CreateJob(Details, Type, args) = dataexchange("POST", "/v1/jobs", args)
CreateJob(a...; b...) = CreateJob(a..., b)

"""
    CreateRevision()

This operation creates a revision for a data set.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set."
}

Optional Parameters
{
  "Comment": "An optional comment about the revision.",
  "Tags": "A revision tag is an optional label that you can assign to a revision when you create it. Each tag consists of a key and an optional value, both of which you define. When you use tagging, you can also use tag-based access control in IAM policies to control access to these data sets and revisions."
}
"""
CreateRevision(DataSetId) = dataexchange("POST", "/v1/data-sets/$(DataSetId)/revisions")
CreateRevision(DataSetId, args) = dataexchange("POST", "/v1/data-sets/$(DataSetId)/revisions", args)
CreateRevision(a...; b...) = CreateRevision(a..., b)

"""
    DeleteAsset()

This operation deletes an asset.

Required Parameters
{
  "AssetId": "The unique identifier for an asset.",
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}
"""
DeleteAsset(AssetId, DataSetId, RevisionId) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)")
DeleteAsset(AssetId, DataSetId, RevisionId, args) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)", args)
DeleteAsset(a...; b...) = DeleteAsset(a..., b)

"""
    DeleteDataSet()

This operation deletes a data set.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set."
}
"""
DeleteDataSet(DataSetId) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)")
DeleteDataSet(DataSetId, args) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)", args)
DeleteDataSet(a...; b...) = DeleteDataSet(a..., b)

"""
    DeleteRevision()

This operation deletes a revision.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}
"""
DeleteRevision(DataSetId, RevisionId) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)")
DeleteRevision(DataSetId, RevisionId, args) = dataexchange("DELETE", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)", args)
DeleteRevision(a...; b...) = DeleteRevision(a..., b)

"""
    GetAsset()

This operation returns information about an asset.

Required Parameters
{
  "AssetId": "The unique identifier for an asset.",
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}
"""
GetAsset(AssetId, DataSetId, RevisionId) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)")
GetAsset(AssetId, DataSetId, RevisionId, args) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)", args)
GetAsset(a...; b...) = GetAsset(a..., b)

"""
    GetDataSet()

This operation returns information about a data set.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set."
}
"""
GetDataSet(DataSetId) = dataexchange("GET", "/v1/data-sets/$(DataSetId)")
GetDataSet(DataSetId, args) = dataexchange("GET", "/v1/data-sets/$(DataSetId)", args)
GetDataSet(a...; b...) = GetDataSet(a..., b)

"""
    GetJob()

This operation returns information about a job.

Required Parameters
{
  "JobId": "The unique identifier for a job."
}
"""
GetJob(JobId) = dataexchange("GET", "/v1/jobs/$(JobId)")
GetJob(JobId, args) = dataexchange("GET", "/v1/jobs/$(JobId)", args)
GetJob(a...; b...) = GetJob(a..., b)

"""
    GetRevision()

This operation returns information about a revision.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}
"""
GetRevision(DataSetId, RevisionId) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)")
GetRevision(DataSetId, RevisionId, args) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)", args)
GetRevision(a...; b...) = GetRevision(a..., b)

"""
    ListDataSetRevisions()

This operation lists a data set's revisions sorted by CreatedAt in descending order.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set."
}

Optional Parameters
{
  "MaxResults": "The maximum number of results returned by a single call.",
  "NextToken": "The token value retrieved from a previous call to access the next page of results."
}
"""
ListDataSetRevisions(DataSetId) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions")
ListDataSetRevisions(DataSetId, args) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions", args)
ListDataSetRevisions(a...; b...) = ListDataSetRevisions(a..., b)

"""
    ListDataSets()

This operation lists your data sets. When listing by origin OWNED, results are sorted by CreatedAt in descending order. When listing by origin ENTITLED, there is no order and the maxResults parameter is ignored.

Optional Parameters
{
  "MaxResults": "The maximum number of results returned by a single call.",
  "NextToken": "The token value retrieved from a previous call to access the next page of results.",
  "Origin": "A property that defines the data set as OWNED by the account (for providers) or ENTITLED to the account (for subscribers)."
}
"""
ListDataSets() = dataexchange("GET", "/v1/data-sets")
ListDataSets(args) = dataexchange("GET", "/v1/data-sets", args)
ListDataSets(a...; b...) = ListDataSets(a..., b)

"""
    ListJobs()

This operation lists your jobs sorted by CreatedAt in descending order.

Optional Parameters
{
  "DataSetId": "The unique identifier for a data set.",
  "MaxResults": "The maximum number of results returned by a single call.",
  "NextToken": "The token value retrieved from a previous call to access the next page of results.",
  "RevisionId": "The unique identifier for a revision."
}
"""
ListJobs() = dataexchange("GET", "/v1/jobs")
ListJobs(args) = dataexchange("GET", "/v1/jobs", args)
ListJobs(a...; b...) = ListJobs(a..., b)

"""
    ListRevisionAssets()

This operation lists a revision's assets sorted alphabetically in descending order.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}

Optional Parameters
{
  "MaxResults": "The maximum number of results returned by a single call.",
  "NextToken": "The token value retrieved from a previous call to access the next page of results."
}
"""
ListRevisionAssets(DataSetId, RevisionId) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets")
ListRevisionAssets(DataSetId, RevisionId, args) = dataexchange("GET", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets", args)
ListRevisionAssets(a...; b...) = ListRevisionAssets(a..., b)

"""
    ListTagsForResource()

This operation lists the tags on the resource.

Required Parameters
{
  "ResourceArn": "An Amazon Resource Name (ARN) that uniquely identifies an AWS resource."
}
"""
ListTagsForResource(ResourceArn) = dataexchange("GET", "/tags/$(resource-arn)")
ListTagsForResource(ResourceArn, args) = dataexchange("GET", "/tags/$(resource-arn)", args)
ListTagsForResource(a...; b...) = ListTagsForResource(a..., b)

"""
    StartJob()

This operation starts a job.

Required Parameters
{
  "JobId": "The unique identifier for a job."
}
"""
StartJob(JobId) = dataexchange("PATCH", "/v1/jobs/$(JobId)")
StartJob(JobId, args) = dataexchange("PATCH", "/v1/jobs/$(JobId)", args)
StartJob(a...; b...) = StartJob(a..., b)

"""
    TagResource()

This operation tags a resource.

Required Parameters
{
  "ResourceArn": "An Amazon Resource Name (ARN) that uniquely identifies an AWS resource.",
  "Tags": "A label that consists of a customer-defined key and an optional value."
}
"""
TagResource(ResourceArn, Tags) = dataexchange("POST", "/tags/$(resource-arn)")
TagResource(ResourceArn, Tags, args) = dataexchange("POST", "/tags/$(resource-arn)", args)
TagResource(a...; b...) = TagResource(a..., b)

"""
    UntagResource()

This operation removes one or more tags from a resource.

Required Parameters
{
  "ResourceArn": "An Amazon Resource Name (ARN) that uniquely identifies an AWS resource.",
  "TagKeys": "The key tags."
}
"""
UntagResource(ResourceArn, TagKeys) = dataexchange("DELETE", "/tags/$(resource-arn)")
UntagResource(ResourceArn, TagKeys, args) = dataexchange("DELETE", "/tags/$(resource-arn)", args)
UntagResource(a...; b...) = UntagResource(a..., b)

"""
    UpdateAsset()

This operation updates an asset.

Required Parameters
{
  "AssetId": "The unique identifier for an asset.",
  "DataSetId": "The unique identifier for a data set.",
  "Name": "The name of the asset. When importing from Amazon S3, the S3 object key is used as the asset name. When exporting to Amazon S3, the asset name is used as default target S3 object key.",
  "RevisionId": "The unique identifier for a revision."
}
"""
UpdateAsset(AssetId, DataSetId, Name, RevisionId) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)")
UpdateAsset(AssetId, DataSetId, Name, RevisionId, args) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)/assets/$(AssetId)", args)
UpdateAsset(a...; b...) = UpdateAsset(a..., b)

"""
    UpdateDataSet()

This operation updates a data set.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set."
}

Optional Parameters
{
  "Description": "The description for the data set.",
  "Name": "The name of the data set."
}
"""
UpdateDataSet(DataSetId) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)")
UpdateDataSet(DataSetId, args) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)", args)
UpdateDataSet(a...; b...) = UpdateDataSet(a..., b)

"""
    UpdateRevision()

This operation updates a revision.

Required Parameters
{
  "DataSetId": "The unique identifier for a data set.",
  "RevisionId": "The unique identifier for a revision."
}

Optional Parameters
{
  "Comment": "An optional comment about the revision.",
  "Finalized": "Finalizing a revision tells AWS Data Exchange that your changes to the assets in the revision are complete. After it's in this read-only state, you can publish the revision to your products."
}
"""
UpdateRevision(DataSetId, RevisionId) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)")
UpdateRevision(DataSetId, RevisionId, args) = dataexchange("PATCH", "/v1/data-sets/$(DataSetId)/revisions/$(RevisionId)", args)
UpdateRevision(a...; b...) = UpdateRevision(a..., b)
