# This file is auto-generated by AWSMetadata.jl
include("../AWSServices.jl")
using Compat
using .AWSServices: medialive

"""
    BatchUpdateSchedule()

Update a channel schedule

Required Parameters
channelId => Id of the channel whose schedule is being updated.

Optional Parameters
creates => Schedule actions to create in the schedule.
deletes => Schedule actions to delete from the schedule.
"""
BatchUpdateSchedule(channelId) = medialive("PUT", "/prod/channels/$(channelId)/schedule")
BatchUpdateSchedule(channelId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/channels/$(channelId)/schedule", args)
BatchUpdateSchedule(a...; b...) = BatchUpdateSchedule(a..., b)

"""
    CreateChannel()

Creates a new channel

Optional Parameters
channelClass => The class for this channel. STANDARD for a channel with two pipelines or SINGLE_PIPELINE for a channel with one pipeline.
destinations => 
encoderSettings => 
inputAttachments => List of input attachments for channel.
inputSpecification => Specification of input for this channel (max. bitrate, resolution, codec, etc.)
logLevel => The log level to write to CloudWatch Logs.
name => Name of channel.
requestId => Unique request ID to be specified. This is needed to prevent retries from
creating multiple resources.

reserved => Deprecated field that's only usable by whitelisted customers.
roleArn => An optional Amazon Resource Name (ARN) of the role to assume when running the Channel.
tags => A collection of key-value pairs.
"""
CreateChannel() = medialive("POST", "/prod/channels")
CreateChannel(args::AbstractDict{String, Any}) = medialive("POST", "/prod/channels", args)
CreateChannel(a...; b...) = CreateChannel(a..., b)

"""
    CreateInput()

Create an input

Optional Parameters
destinations => Destination settings for PUSH type inputs.
inputDevices => Settings for the devices.
inputSecurityGroups => A list of security groups referenced by IDs to attach to the input.
mediaConnectFlows => A list of the MediaConnect Flows that you want to use in this input. You can specify as few as one
Flow and presently, as many as two. The only requirement is when you have more than one is that each Flow is in a
separate Availability Zone as this ensures your EML input is redundant to AZ issues.

name => Name of the input.
requestId => Unique identifier of the request to ensure the request is handled
exactly once in case of retries.

roleArn => The Amazon Resource Name (ARN) of the role this input assumes during and after creation.
sources => The source URLs for a PULL-type input. Every PULL type input needs
exactly two source URLs for redundancy.
Only specify sources for PULL type Inputs. Leave Destinations empty.

tags => A collection of key-value pairs.
type => 
vpc => 
"""
CreateInput() = medialive("POST", "/prod/inputs")
CreateInput(args::AbstractDict{String, Any}) = medialive("POST", "/prod/inputs", args)
CreateInput(a...; b...) = CreateInput(a..., b)

"""
    CreateInputSecurityGroup()

Creates a Input Security Group

Optional Parameters
tags => A collection of key-value pairs.
whitelistRules => List of IPv4 CIDR addresses to whitelist
"""
CreateInputSecurityGroup() = medialive("POST", "/prod/inputSecurityGroups")
CreateInputSecurityGroup(args::AbstractDict{String, Any}) = medialive("POST", "/prod/inputSecurityGroups", args)
CreateInputSecurityGroup(a...; b...) = CreateInputSecurityGroup(a..., b)

"""
    CreateMultiplex()

Create a new multiplex.

Required Parameters
availabilityZones => A list of availability zones for the multiplex. You must specify exactly two.
multiplexSettings => Configuration for a multiplex event.
name => Name of multiplex.
requestId => Unique request ID. This prevents retries from creating multiple
resources.


Optional Parameters
tags => A collection of key-value pairs.
"""
CreateMultiplex(availabilityZones, multiplexSettings, name, requestId) = medialive("POST", "/prod/multiplexes", Dict{String, Any}("availabilityZones"=>availabilityZones, "multiplexSettings"=>multiplexSettings, "name"=>name, "requestId"=>requestId))
CreateMultiplex(availabilityZones, multiplexSettings, name, requestId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/multiplexes", Dict{String, Any}("availabilityZones"=>availabilityZones, "multiplexSettings"=>multiplexSettings, "name"=>name, "requestId"=>requestId, args...))
CreateMultiplex(a...; b...) = CreateMultiplex(a..., b)

"""
    CreateMultiplexProgram()

Create a new program in the multiplex.

Required Parameters
multiplexId => ID of the multiplex where the program is to be created.
multiplexProgramSettings => The settings for this multiplex program.
programName => Name of multiplex program.
requestId => Unique request ID. This prevents retries from creating multiple
resources.


"""
CreateMultiplexProgram(multiplexId, multiplexProgramSettings, programName, requestId) = medialive("POST", "/prod/multiplexes/$(multiplexId)/programs", Dict{String, Any}("multiplexProgramSettings"=>multiplexProgramSettings, "programName"=>programName, "requestId"=>requestId))
CreateMultiplexProgram(multiplexId, multiplexProgramSettings, programName, requestId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/multiplexes/$(multiplexId)/programs", Dict{String, Any}("multiplexProgramSettings"=>multiplexProgramSettings, "programName"=>programName, "requestId"=>requestId, args...))
CreateMultiplexProgram(a...; b...) = CreateMultiplexProgram(a..., b)

"""
    CreateTags()

Create tags for a resource

Required Parameters
resource-arn => 

Optional Parameters
tags => 
"""
CreateTags(resource_arn) = medialive("POST", "/prod/tags/$(resource-arn)")
CreateTags(resource_arn, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/tags/$(resource-arn)", args)
CreateTags(a...; b...) = CreateTags(a..., b)

"""
    DeleteChannel()

Starts deletion of channel. The associated outputs are also deleted.

Required Parameters
channelId => Unique ID of the channel.

"""
DeleteChannel(channelId) = medialive("DELETE", "/prod/channels/$(channelId)")
DeleteChannel(channelId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/channels/$(channelId)", args)
DeleteChannel(a...; b...) = DeleteChannel(a..., b)

"""
    DeleteInput()

Deletes the input end point

Required Parameters
inputId => Unique ID of the input

"""
DeleteInput(inputId) = medialive("DELETE", "/prod/inputs/$(inputId)")
DeleteInput(inputId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/inputs/$(inputId)", args)
DeleteInput(a...; b...) = DeleteInput(a..., b)

"""
    DeleteInputSecurityGroup()

Deletes an Input Security Group

Required Parameters
inputSecurityGroupId => The Input Security Group to delete

"""
DeleteInputSecurityGroup(inputSecurityGroupId) = medialive("DELETE", "/prod/inputSecurityGroups/$(inputSecurityGroupId)")
DeleteInputSecurityGroup(inputSecurityGroupId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/inputSecurityGroups/$(inputSecurityGroupId)", args)
DeleteInputSecurityGroup(a...; b...) = DeleteInputSecurityGroup(a..., b)

"""
    DeleteMultiplex()

Delete a multiplex. The multiplex must be idle.

Required Parameters
multiplexId => The ID of the multiplex.

"""
DeleteMultiplex(multiplexId) = medialive("DELETE", "/prod/multiplexes/$(multiplexId)")
DeleteMultiplex(multiplexId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/multiplexes/$(multiplexId)", args)
DeleteMultiplex(a...; b...) = DeleteMultiplex(a..., b)

"""
    DeleteMultiplexProgram()

Delete a program from a multiplex.

Required Parameters
multiplexId => The ID of the multiplex that the program belongs to.
programName => The multiplex program name.

"""
DeleteMultiplexProgram(multiplexId, programName) = medialive("DELETE", "/prod/multiplexes/$(multiplexId)/programs/$(programName)")
DeleteMultiplexProgram(multiplexId, programName, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/multiplexes/$(multiplexId)/programs/$(programName)", args)
DeleteMultiplexProgram(a...; b...) = DeleteMultiplexProgram(a..., b)

"""
    DeleteReservation()

Delete an expired reservation.

Required Parameters
reservationId => Unique reservation ID, e.g. '1234567'

"""
DeleteReservation(reservationId) = medialive("DELETE", "/prod/reservations/$(reservationId)")
DeleteReservation(reservationId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/reservations/$(reservationId)", args)
DeleteReservation(a...; b...) = DeleteReservation(a..., b)

"""
    DeleteSchedule()

Delete all schedule actions on a channel.

Required Parameters
channelId => Id of the channel whose schedule is being deleted.

"""
DeleteSchedule(channelId) = medialive("DELETE", "/prod/channels/$(channelId)/schedule")
DeleteSchedule(channelId, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/channels/$(channelId)/schedule", args)
DeleteSchedule(a...; b...) = DeleteSchedule(a..., b)

"""
    DeleteTags()

Removes tags for a resource

Required Parameters
resource-arn => 
tagKeys => An array of tag keys to delete

"""
DeleteTags(resource_arn, tagKeys) = medialive("DELETE", "/prod/tags/$(resource-arn)", Dict{String, Any}("tagKeys"=>tagKeys))
DeleteTags(resource_arn, tagKeys, args::AbstractDict{String, <: Any}) = medialive("DELETE", "/prod/tags/$(resource-arn)", Dict{String, Any}("tagKeys"=>tagKeys, args...))
DeleteTags(a...; b...) = DeleteTags(a..., b)

"""
    DescribeChannel()

Gets details about a channel

Required Parameters
channelId => channel ID

"""
DescribeChannel(channelId) = medialive("GET", "/prod/channels/$(channelId)")
DescribeChannel(channelId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/channels/$(channelId)", args)
DescribeChannel(a...; b...) = DescribeChannel(a..., b)

"""
    DescribeInput()

Produces details about an input

Required Parameters
inputId => Unique ID of the input

"""
DescribeInput(inputId) = medialive("GET", "/prod/inputs/$(inputId)")
DescribeInput(inputId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/inputs/$(inputId)", args)
DescribeInput(a...; b...) = DescribeInput(a..., b)

"""
    DescribeInputDevice()

Gets the details for the input device

Required Parameters
inputDeviceId => The unique ID of this input device. For example, hd-123456789abcdef.

"""
DescribeInputDevice(inputDeviceId) = medialive("GET", "/prod/inputDevices/$(inputDeviceId)")
DescribeInputDevice(inputDeviceId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/inputDevices/$(inputDeviceId)", args)
DescribeInputDevice(a...; b...) = DescribeInputDevice(a..., b)

"""
    DescribeInputDeviceThumbnail()

Get the latest thumbnail data for the input device.

Required Parameters
accept => The HTTP Accept header. Indicates the requested type for the thumbnail.
inputDeviceId => The unique ID of this input device. For example, hd-123456789abcdef.

"""
DescribeInputDeviceThumbnail(accept, inputDeviceId) = medialive("GET", "/prod/inputDevices/$(inputDeviceId)/thumbnailData", Dict{String, Any}("headers"=>Dict{String, Any}("accept"=>accept)))
DescribeInputDeviceThumbnail(accept, inputDeviceId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/inputDevices/$(inputDeviceId)/thumbnailData", Dict{String, Any}(mergewith(merge, Dict{String, Any}("headers"=>Dict{String, Any}("accept"=>accept)), args...)))
DescribeInputDeviceThumbnail(a...; b...) = DescribeInputDeviceThumbnail(a..., b)

"""
    DescribeInputSecurityGroup()

Produces a summary of an Input Security Group

Required Parameters
inputSecurityGroupId => The id of the Input Security Group to describe

"""
DescribeInputSecurityGroup(inputSecurityGroupId) = medialive("GET", "/prod/inputSecurityGroups/$(inputSecurityGroupId)")
DescribeInputSecurityGroup(inputSecurityGroupId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/inputSecurityGroups/$(inputSecurityGroupId)", args)
DescribeInputSecurityGroup(a...; b...) = DescribeInputSecurityGroup(a..., b)

"""
    DescribeMultiplex()

Gets details about a multiplex.

Required Parameters
multiplexId => The ID of the multiplex.

"""
DescribeMultiplex(multiplexId) = medialive("GET", "/prod/multiplexes/$(multiplexId)")
DescribeMultiplex(multiplexId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/multiplexes/$(multiplexId)", args)
DescribeMultiplex(a...; b...) = DescribeMultiplex(a..., b)

"""
    DescribeMultiplexProgram()

Get the details for a program in a multiplex.

Required Parameters
multiplexId => The ID of the multiplex that the program belongs to.
programName => The name of the program.

"""
DescribeMultiplexProgram(multiplexId, programName) = medialive("GET", "/prod/multiplexes/$(multiplexId)/programs/$(programName)")
DescribeMultiplexProgram(multiplexId, programName, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/multiplexes/$(multiplexId)/programs/$(programName)", args)
DescribeMultiplexProgram(a...; b...) = DescribeMultiplexProgram(a..., b)

"""
    DescribeOffering()

Get details for an offering.

Required Parameters
offeringId => Unique offering ID, e.g. '87654321'

"""
DescribeOffering(offeringId) = medialive("GET", "/prod/offerings/$(offeringId)")
DescribeOffering(offeringId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/offerings/$(offeringId)", args)
DescribeOffering(a...; b...) = DescribeOffering(a..., b)

"""
    DescribeReservation()

Get details for a reservation.

Required Parameters
reservationId => Unique reservation ID, e.g. '1234567'

"""
DescribeReservation(reservationId) = medialive("GET", "/prod/reservations/$(reservationId)")
DescribeReservation(reservationId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/reservations/$(reservationId)", args)
DescribeReservation(a...; b...) = DescribeReservation(a..., b)

"""
    DescribeSchedule()

Get a channel schedule

Required Parameters
channelId => Id of the channel whose schedule is being updated.

Optional Parameters
maxResults => 
nextToken => 
"""
DescribeSchedule(channelId) = medialive("GET", "/prod/channels/$(channelId)/schedule")
DescribeSchedule(channelId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/channels/$(channelId)/schedule", args)
DescribeSchedule(a...; b...) = DescribeSchedule(a..., b)

"""
    ListChannels()

Produces list of channels that have been created

Optional Parameters
maxResults => 
nextToken => 
"""
ListChannels() = medialive("GET", "/prod/channels")
ListChannels(args::AbstractDict{String, Any}) = medialive("GET", "/prod/channels", args)
ListChannels(a...; b...) = ListChannels(a..., b)

"""
    ListInputDevices()

List input devices

Optional Parameters
maxResults => 
nextToken => 
"""
ListInputDevices() = medialive("GET", "/prod/inputDevices")
ListInputDevices(args::AbstractDict{String, Any}) = medialive("GET", "/prod/inputDevices", args)
ListInputDevices(a...; b...) = ListInputDevices(a..., b)

"""
    ListInputSecurityGroups()

Produces a list of Input Security Groups for an account

Optional Parameters
maxResults => 
nextToken => 
"""
ListInputSecurityGroups() = medialive("GET", "/prod/inputSecurityGroups")
ListInputSecurityGroups(args::AbstractDict{String, Any}) = medialive("GET", "/prod/inputSecurityGroups", args)
ListInputSecurityGroups(a...; b...) = ListInputSecurityGroups(a..., b)

"""
    ListInputs()

Produces list of inputs that have been created

Optional Parameters
maxResults => 
nextToken => 
"""
ListInputs() = medialive("GET", "/prod/inputs")
ListInputs(args::AbstractDict{String, Any}) = medialive("GET", "/prod/inputs", args)
ListInputs(a...; b...) = ListInputs(a..., b)

"""
    ListMultiplexPrograms()

List the programs that currently exist for a specific multiplex.

Required Parameters
multiplexId => The ID of the multiplex that the programs belong to.

Optional Parameters
maxResults => The maximum number of items to return.
nextToken => The token to retrieve the next page of results.
"""
ListMultiplexPrograms(multiplexId) = medialive("GET", "/prod/multiplexes/$(multiplexId)/programs")
ListMultiplexPrograms(multiplexId, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/multiplexes/$(multiplexId)/programs", args)
ListMultiplexPrograms(a...; b...) = ListMultiplexPrograms(a..., b)

"""
    ListMultiplexes()

Retrieve a list of the existing multiplexes.

Optional Parameters
maxResults => The maximum number of items to return.
nextToken => The token to retrieve the next page of results.
"""
ListMultiplexes() = medialive("GET", "/prod/multiplexes")
ListMultiplexes(args::AbstractDict{String, Any}) = medialive("GET", "/prod/multiplexes", args)
ListMultiplexes(a...; b...) = ListMultiplexes(a..., b)

"""
    ListOfferings()

List offerings available for purchase.

Optional Parameters
channelClass => Filter by channel class, 'STANDARD' or 'SINGLE_PIPELINE'

channelConfiguration => Filter to offerings that match the configuration of an existing channel, e.g. '2345678' (a channel ID)

codec => Filter by codec, 'AVC', 'HEVC', 'MPEG2', or 'AUDIO'
duration => Filter by offering duration, e.g. '12'
maxResults => 
maximumBitrate => Filter by bitrate, 'MAX_10_MBPS', 'MAX_20_MBPS', or 'MAX_50_MBPS'

maximumFramerate => Filter by framerate, 'MAX_30_FPS' or 'MAX_60_FPS'
nextToken => 
resolution => Filter by resolution, 'SD', 'HD', 'FHD', or 'UHD'
resourceType => Filter by resource type, 'INPUT', 'OUTPUT', 'MULTIPLEX', or 'CHANNEL'
specialFeature => Filter by special feature, 'ADVANCED_AUDIO' or 'AUDIO_NORMALIZATION'

videoQuality => Filter by video quality, 'STANDARD', 'ENHANCED', or 'PREMIUM'

"""
ListOfferings() = medialive("GET", "/prod/offerings")
ListOfferings(args::AbstractDict{String, Any}) = medialive("GET", "/prod/offerings", args)
ListOfferings(a...; b...) = ListOfferings(a..., b)

"""
    ListReservations()

List purchased reservations.

Optional Parameters
channelClass => Filter by channel class, 'STANDARD' or 'SINGLE_PIPELINE'

codec => Filter by codec, 'AVC', 'HEVC', 'MPEG2', or 'AUDIO'
maxResults => 
maximumBitrate => Filter by bitrate, 'MAX_10_MBPS', 'MAX_20_MBPS', or 'MAX_50_MBPS'

maximumFramerate => Filter by framerate, 'MAX_30_FPS' or 'MAX_60_FPS'
nextToken => 
resolution => Filter by resolution, 'SD', 'HD', 'FHD', or 'UHD'
resourceType => Filter by resource type, 'INPUT', 'OUTPUT', 'MULTIPLEX', or 'CHANNEL'
specialFeature => Filter by special feature, 'ADVANCED_AUDIO' or 'AUDIO_NORMALIZATION'

videoQuality => Filter by video quality, 'STANDARD', 'ENHANCED', or 'PREMIUM'

"""
ListReservations() = medialive("GET", "/prod/reservations")
ListReservations(args::AbstractDict{String, Any}) = medialive("GET", "/prod/reservations", args)
ListReservations(a...; b...) = ListReservations(a..., b)

"""
    ListTagsForResource()

Produces list of tags that have been created for a resource

Required Parameters
resource-arn => 

"""
ListTagsForResource(resource_arn) = medialive("GET", "/prod/tags/$(resource-arn)")
ListTagsForResource(resource_arn, args::AbstractDict{String, <: Any}) = medialive("GET", "/prod/tags/$(resource-arn)", args)
ListTagsForResource(a...; b...) = ListTagsForResource(a..., b)

"""
    PurchaseOffering()

Purchase an offering and create a reservation.

Required Parameters
count => Number of resources
offeringId => Offering to purchase, e.g. '87654321'

Optional Parameters
name => Name for the new reservation
requestId => Unique request ID to be specified. This is needed to prevent retries from creating multiple resources.
start => Requested reservation start time (UTC) in ISO-8601 format. The specified time must be between the first day of the current month and one year from now. If no value is given, the default is now.
tags => A collection of key-value pairs
"""
PurchaseOffering(count, offeringId) = medialive("POST", "/prod/offerings/$(offeringId)/purchase", Dict{String, Any}("count"=>count))
PurchaseOffering(count, offeringId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/offerings/$(offeringId)/purchase", Dict{String, Any}("count"=>count, args...))
PurchaseOffering(a...; b...) = PurchaseOffering(a..., b)

"""
    StartChannel()

Starts an existing channel

Required Parameters
channelId => A request to start a channel

"""
StartChannel(channelId) = medialive("POST", "/prod/channels/$(channelId)/start")
StartChannel(channelId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/channels/$(channelId)/start", args)
StartChannel(a...; b...) = StartChannel(a..., b)

"""
    StartMultiplex()

Start (run) the multiplex. Starting the multiplex does not start the channels. You must explicitly start each channel.

Required Parameters
multiplexId => The ID of the multiplex.

"""
StartMultiplex(multiplexId) = medialive("POST", "/prod/multiplexes/$(multiplexId)/start")
StartMultiplex(multiplexId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/multiplexes/$(multiplexId)/start", args)
StartMultiplex(a...; b...) = StartMultiplex(a..., b)

"""
    StopChannel()

Stops a running channel

Required Parameters
channelId => A request to stop a running channel

"""
StopChannel(channelId) = medialive("POST", "/prod/channels/$(channelId)/stop")
StopChannel(channelId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/channels/$(channelId)/stop", args)
StopChannel(a...; b...) = StopChannel(a..., b)

"""
    StopMultiplex()

Stops a running multiplex. If the multiplex isn't running, this action has no effect.

Required Parameters
multiplexId => The ID of the multiplex.

"""
StopMultiplex(multiplexId) = medialive("POST", "/prod/multiplexes/$(multiplexId)/stop")
StopMultiplex(multiplexId, args::AbstractDict{String, <: Any}) = medialive("POST", "/prod/multiplexes/$(multiplexId)/stop", args)
StopMultiplex(a...; b...) = StopMultiplex(a..., b)

"""
    UpdateChannel()

Updates a channel.

Required Parameters
channelId => channel ID

Optional Parameters
destinations => A list of output destinations for this channel.
encoderSettings => The encoder settings for this channel.
inputAttachments => 
inputSpecification => Specification of input for this channel (max. bitrate, resolution, codec, etc.)
logLevel => The log level to write to CloudWatch Logs.
name => The name of the channel.
roleArn => An optional Amazon Resource Name (ARN) of the role to assume when running the Channel. If you do not specify this on an update call but the role was previously set that role will be removed.
"""
UpdateChannel(channelId) = medialive("PUT", "/prod/channels/$(channelId)")
UpdateChannel(channelId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/channels/$(channelId)", args)
UpdateChannel(a...; b...) = UpdateChannel(a..., b)

"""
    UpdateChannelClass()

Changes the class of the channel.

Required Parameters
channelClass => The channel class that you wish to update this channel to use.
channelId => Channel Id of the channel whose class should be updated.

Optional Parameters
destinations => A list of output destinations for this channel.
"""
UpdateChannelClass(channelClass, channelId) = medialive("PUT", "/prod/channels/$(channelId)/channelClass", Dict{String, Any}("channelClass"=>channelClass))
UpdateChannelClass(channelClass, channelId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/channels/$(channelId)/channelClass", Dict{String, Any}("channelClass"=>channelClass, args...))
UpdateChannelClass(a...; b...) = UpdateChannelClass(a..., b)

"""
    UpdateInput()

Updates an input.

Required Parameters
inputId => Unique ID of the input.

Optional Parameters
destinations => Destination settings for PUSH type inputs.
inputDevices => Settings for the devices.
inputSecurityGroups => A list of security groups referenced by IDs to attach to the input.
mediaConnectFlows => A list of the MediaConnect Flow ARNs that you want to use as the source of the input. You can specify as few as one
Flow and presently, as many as two. The only requirement is when you have more than one is that each Flow is in a
separate Availability Zone as this ensures your EML input is redundant to AZ issues.

name => Name of the input.
roleArn => The Amazon Resource Name (ARN) of the role this input assumes during and after creation.
sources => The source URLs for a PULL-type input. Every PULL type input needs
exactly two source URLs for redundancy.
Only specify sources for PULL type Inputs. Leave Destinations empty.

"""
UpdateInput(inputId) = medialive("PUT", "/prod/inputs/$(inputId)")
UpdateInput(inputId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/inputs/$(inputId)", args)
UpdateInput(a...; b...) = UpdateInput(a..., b)

"""
    UpdateInputDevice()

Updates the parameters for the input device.

Required Parameters
inputDeviceId => The unique ID of the input device. For example, hd-123456789abcdef.

Optional Parameters
hdDeviceSettings => The settings that you want to apply to the input device.
name => The name that you assigned to this input device (not the unique ID).
"""
UpdateInputDevice(inputDeviceId) = medialive("PUT", "/prod/inputDevices/$(inputDeviceId)")
UpdateInputDevice(inputDeviceId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/inputDevices/$(inputDeviceId)", args)
UpdateInputDevice(a...; b...) = UpdateInputDevice(a..., b)

"""
    UpdateInputSecurityGroup()

Update an Input Security Group's Whilelists.

Required Parameters
inputSecurityGroupId => The id of the Input Security Group to update.

Optional Parameters
tags => A collection of key-value pairs.
whitelistRules => List of IPv4 CIDR addresses to whitelist
"""
UpdateInputSecurityGroup(inputSecurityGroupId) = medialive("PUT", "/prod/inputSecurityGroups/$(inputSecurityGroupId)")
UpdateInputSecurityGroup(inputSecurityGroupId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/inputSecurityGroups/$(inputSecurityGroupId)", args)
UpdateInputSecurityGroup(a...; b...) = UpdateInputSecurityGroup(a..., b)

"""
    UpdateMultiplex()

Updates a multiplex.

Required Parameters
multiplexId => ID of the multiplex to update.

Optional Parameters
multiplexSettings => The new settings for a multiplex.
name => Name of the multiplex.
"""
UpdateMultiplex(multiplexId) = medialive("PUT", "/prod/multiplexes/$(multiplexId)")
UpdateMultiplex(multiplexId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/multiplexes/$(multiplexId)", args)
UpdateMultiplex(a...; b...) = UpdateMultiplex(a..., b)

"""
    UpdateMultiplexProgram()

Update a program in a multiplex.

Required Parameters
multiplexId => The ID of the multiplex of the program to update.
programName => The name of the program to update.

Optional Parameters
multiplexProgramSettings => The new settings for a multiplex program.
"""
UpdateMultiplexProgram(multiplexId, programName) = medialive("PUT", "/prod/multiplexes/$(multiplexId)/programs/$(programName)")
UpdateMultiplexProgram(multiplexId, programName, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/multiplexes/$(multiplexId)/programs/$(programName)", args)
UpdateMultiplexProgram(a...; b...) = UpdateMultiplexProgram(a..., b)

"""
    UpdateReservation()

Update reservation.

Required Parameters
reservationId => Unique reservation ID, e.g. '1234567'

Optional Parameters
name => Name of the reservation
"""
UpdateReservation(reservationId) = medialive("PUT", "/prod/reservations/$(reservationId)")
UpdateReservation(reservationId, args::AbstractDict{String, <: Any}) = medialive("PUT", "/prod/reservations/$(reservationId)", args)
UpdateReservation(a...; b...) = UpdateReservation(a..., b)
