# This file is auto-generated by AWSMetadata.jl
using AWS
using AWS.AWSServices: mobile

using Compat
using UUIDs
"""
    CreateProject()

 Creates an AWS Mobile Hub project. 

# Optional Parameters
- `contents`:  ZIP or YAML file which contains configuration settings to be used when creating the project. This may be the contents of the file downloaded from the URL provided in an export project operation. 
- `name`:  Name of the project. 
- `region`:  Default region where project resources should be created. 
- `snapshotId`:  Unique identifier for an exported snapshot of project configuration. This snapshot identifier is included in the share URL when a project is exported. 
"""
CreateProject(; aws::AWSConfig=AWSConfig()) = mobile("POST", "/projects"; aws=aws)
CreateProject(args::AbstractDict{String, Any}; aws::AWSConfig=AWSConfig()) = mobile("POST", "/projects", args; aws=aws)

"""
    DeleteProject()

 Delets a project in AWS Mobile Hub. 

# Required Parameters
- `projectId`:  Unique project identifier. 

"""
DeleteProject(projectId; aws::AWSConfig=AWSConfig()) = mobile("DELETE", "/projects/$(projectId)"; aws=aws)
DeleteProject(projectId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("DELETE", "/projects/$(projectId)", args; aws=aws)

"""
    DescribeBundle()

 Get the bundle details for the requested bundle id. 

# Required Parameters
- `bundleId`:  Unique bundle identifier. 

"""
DescribeBundle(bundleId; aws::AWSConfig=AWSConfig()) = mobile("GET", "/bundles/$(bundleId)"; aws=aws)
DescribeBundle(bundleId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("GET", "/bundles/$(bundleId)", args; aws=aws)

"""
    DescribeProject()

 Gets details about a project in AWS Mobile Hub. 

# Required Parameters
- `projectId`:  Unique project identifier. 

# Optional Parameters
- `syncFromResources`:  If set to true, causes AWS Mobile Hub to synchronize information from other services, e.g., update state of AWS CloudFormation stacks in the AWS Mobile Hub project. 
"""
DescribeProject(projectId; aws::AWSConfig=AWSConfig()) = mobile("GET", "/project", Dict{String, Any}("projectId"=>projectId))
DescribeProject(projectId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("GET", "/project", Dict{String, Any}(mergewith(_merge, Dict{String, Any}("projectId"=>projectId), args)); aws=aws)

"""
    ExportBundle()

 Generates customized software development kit (SDK) and or tool packages used to integrate mobile web or mobile app clients with backend AWS resources. 

# Required Parameters
- `bundleId`:  Unique bundle identifier. 

# Optional Parameters
- `platform`:  Developer desktop or target application platform. 
- `projectId`:  Unique project identifier. 
"""
ExportBundle(bundleId; aws::AWSConfig=AWSConfig()) = mobile("POST", "/bundles/$(bundleId)"; aws=aws)
ExportBundle(bundleId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("POST", "/bundles/$(bundleId)", args; aws=aws)

"""
    ExportProject()

 Exports project configuration to a snapshot which can be downloaded and shared. Note that mobile app push credentials are encrypted in exported projects, so they can only be shared successfully within the same AWS account. 

# Required Parameters
- `projectId`:  Unique project identifier. 

"""
ExportProject(projectId; aws::AWSConfig=AWSConfig()) = mobile("POST", "/exports/$(projectId)"; aws=aws)
ExportProject(projectId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("POST", "/exports/$(projectId)", args; aws=aws)

"""
    ListBundles()

 List all available bundles. 

# Optional Parameters
- `maxResults`:  Maximum number of records to list in a single response. 
- `nextToken`:  Pagination token. Set to null to start listing bundles from start. If non-null pagination token is returned in a result, then pass its value in here in another request to list more bundles. 
"""
ListBundles(; aws::AWSConfig=AWSConfig()) = mobile("GET", "/bundles"; aws=aws)
ListBundles(args::AbstractDict{String, Any}; aws::AWSConfig=AWSConfig()) = mobile("GET", "/bundles", args; aws=aws)

"""
    ListProjects()

 Lists projects in AWS Mobile Hub. 

# Optional Parameters
- `maxResults`:  Maximum number of records to list in a single response. 
- `nextToken`:  Pagination token. Set to null to start listing projects from start. If non-null pagination token is returned in a result, then pass its value in here in another request to list more projects. 
"""
ListProjects(; aws::AWSConfig=AWSConfig()) = mobile("GET", "/projects"; aws=aws)
ListProjects(args::AbstractDict{String, Any}; aws::AWSConfig=AWSConfig()) = mobile("GET", "/projects", args; aws=aws)

"""
    UpdateProject()

 Update an existing project. 

# Required Parameters
- `projectId`:  Unique project identifier. 

# Optional Parameters
- `contents`:  ZIP or YAML file which contains project configuration to be updated. This should be the contents of the file downloaded from the URL provided in an export project operation. 
"""
UpdateProject(projectId; aws::AWSConfig=AWSConfig()) = mobile("POST", "/update", Dict{String, Any}("projectId"=>projectId))
UpdateProject(projectId, args::AbstractDict{String, <:Any}; aws::AWSConfig=AWSConfig()) = mobile("POST", "/update", Dict{String, Any}(mergewith(_merge, Dict{String, Any}("projectId"=>projectId), args)); aws=aws)
